== QuickStart Guide

Why is Atlas great? How can I get up and running in 5 minutes or less? read on!

=== Why Is Atlas Great?

* Text goes here

=== Signing Up and Logging In

* Text goes here

=== Creating a New project

* Go to the Your Books tab and click "New Book". Enter the Title, click the button, and your book is ready to go.

* Add files by "Open Editor" on the Dashboard, or click the Write tab. If you haven't created any files yet, you'll be prompted to do so before you start writing.

* To create new files, click the Switch File button at the top right of the editing pane, and choose "new File" from the bottom.

* Use the formatting buttons along the top to add asciidoc markup to your text, as well as insert images, videos, 3D models, and more.

* Invite Collabortaors by clicking the Collaborators button in the toolbar, and entering the email address of the person you'd like to add.

=== Building a Project

* Text goes here

=== Publishing to Chimera

* Text goes here